version: "3"
services:
    gateway:
        build: ./src/gateway.js
        ports:
            - "8000:8000" # Предполагается, что gateway слушает порт 8000
        depends_on:
            - m1
            - m2

    m1:
        build: ./src/m1.js
        # Порты для m1 не открываются, если они не нужны вне Docker сети

    m2:
        build: ./src/m2.js
        # Порты для m2 не открываются, если они не нужны вне Docker сети

networks:
    default:
        driver: bridge
